FROM mysql:latest

WORKDIR /app

COPY ./schema.sql .
COPY ./tablas.sql .
COPY ./data.sql .

ENV MYSQL_ROOT_PASSWORD=root

RUN cat schema.sql | mysql -u root -proot
RUN cat tablas.sql | mysql -u root -proot
RUN cat data.sql | mysql -u root -proot
