FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=metodosagiles
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=root

# Copy SQL scripts to initialize the database
COPY 01_schema.sql /docker-entrypoint-initdb.d/
COPY 02_tablas.sql /docker-entrypoint-initdb.d/
COPY 03_data.sql /docker-entrypoint-initdb.d/
COPY 04_seq.sql /docker-entrypoint-initdb.d/

# Expose the default MySQL port
EXPOSE 3306