/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.metodos.licencias.view;

import com.metodos.licencias.DTO.TitularDTO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author valec
 */
public class ComprobanteFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComprobanteFrame
     */
    public ComprobanteFrame(TitularDTO titularDTO, Double costo) {
        initComponents();
         //creacion Frame
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        ImageIcon customIcon = new ImageIcon("logo.png");
        setIconImage(customIcon.getImage());
    
        //inicializo container
        JPanel comprobantePanel = new ComprobantePanel(titularDTO,costo,this);
        setContentPane(comprobantePanel);
        
        pack();
        setSize(800, 900);
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
