/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.metodos.licencias.view;

import org.springframework.stereotype.Component;

import com.metodos.licencias.DTO.LicenciaDTO;
import com.metodos.licencias.DTO.TitularDTO;
import com.metodos.licencias.logic.TipoDocumento;
import com.metodos.licencias.util.Item;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author valec
 */
@Component
public class InfoTitular extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    
    private int cornerRadius = 15;
    private TitularesMain main;
    private Color grisOscuro = new Color(80,80,80);
    
    public InfoTitular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new RoundedPanel(30);
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mod_titular_gruposanguineo = new RoundedComboBox(cornerRadius, grisOscuro);
        jLabel5 = new javax.swing.JLabel();
        Mod_titular_fechanac = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Mod_titular_tipodni = new RoundedComboBox(cornerRadius, grisOscuro);
        jLabel18 = new javax.swing.JLabel();
        Mod_titular_editar1 = new RoundedButton(cornerRadius);
        jLabel10 = new javax.swing.JLabel();
        mod_titular_apellido = new RoundedTextField(cornerRadius,grisOscuro);
        mod_titular_nombre = new RoundedTextField(cornerRadius,grisOscuro);
        mod_titular_nroDNI = new RoundedTextField(cornerRadius,grisOscuro);
        mod_titular_calle = new RoundedTextField(cornerRadius,grisOscuro);
        mod_titular_altura = new RoundedTextField(cornerRadius,grisOscuro);
        mod_titular_esDonante = new javax.swing.JCheckBox();
        mod_titular_volverBtn = new RoundedButton(cornerRadius);
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(30);
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Licencias_tabla = new javax.swing.JTable();
        Licencias_emitirCopia_btn = new RoundedButton(cornerRadius);
        Licencias_emitir_btn = new RoundedButton(cornerRadius);
        Licencias_renovar_btn = new RoundedButton(cornerRadius);
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Licencias_emitir_clase = new RoundedComboBox(cornerRadius, grisOscuro);
        jScrollPane2 = new javax.swing.JScrollPane();
        mod_titular_observaciones = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(194, 194, 194));
        setForeground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(1200, 620));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 30);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setText("Tipo DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Número DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 30);
        jPanel1.add(jLabel4, gridBagConstraints);

        Mod_titular_gruposanguineo.setBackground(new java.awt.Color(252, 252, 252));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(Mod_titular_gruposanguineo, gridBagConstraints);

        jLabel5.setText("Fecha Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 30);
        jPanel1.add(jLabel5, gridBagConstraints);

        Mod_titular_fechanac.setBackground(new java.awt.Color(220, 220, 220));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(Mod_titular_fechanac, gridBagConstraints);

        jLabel6.setText("Grupo Sanguíneo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel11.setText("Calle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Altura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 30);
        jPanel1.add(jLabel12, gridBagConstraints);

        Mod_titular_tipodni.setBackground(new java.awt.Color(252, 252, 252));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(Mod_titular_tipodni, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Información del titular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jLabel18, gridBagConstraints);

        Mod_titular_editar1.setBackground(new java.awt.Color(27, 140, 188));
        Mod_titular_editar1.setForeground(new java.awt.Color(255, 255, 255));
        Mod_titular_editar1.setText("Editar");
        Mod_titular_editar1.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 30);
        jPanel1.add(Mod_titular_editar1, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Datos Personales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        mod_titular_apellido.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(mod_titular_apellido, gridBagConstraints);

        mod_titular_nombre.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(mod_titular_nombre, gridBagConstraints);

        mod_titular_nroDNI.setText("jTextField3");
        mod_titular_nroDNI.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(mod_titular_nroDNI, gridBagConstraints);

        mod_titular_calle.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(mod_titular_calle, gridBagConstraints);

        mod_titular_altura.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(mod_titular_altura, gridBagConstraints);

        mod_titular_esDonante.setBackground(new java.awt.Color(252, 252, 252));
        mod_titular_esDonante.setText("Es donante de órganos");
        mod_titular_esDonante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_titular_esDonanteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 15);
        jPanel1.add(mod_titular_esDonante, gridBagConstraints);

        mod_titular_volverBtn.setBackground(new java.awt.Color(204, 204, 204));
        mod_titular_volverBtn.setForeground(new java.awt.Color(51, 51, 51));
        mod_titular_volverBtn.setText("Volver");
        mod_titular_volverBtn.setBorder(null);
        mod_titular_volverBtn.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel1.add(mod_titular_volverBtn, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Licencias solicitadas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        Licencias_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Licencia", "Inicio vigencia", "Fin vigencia", "Activa", "Clase"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Licencias_tabla);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 614;
        gridBagConstraints.ipady = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 30, 0, 42);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        Licencias_emitirCopia_btn.setBackground(new java.awt.Color(27, 140, 188));
        Licencias_emitirCopia_btn.setForeground(new java.awt.Color(255, 255, 255));
        Licencias_emitirCopia_btn.setText("Emitir copia");
        Licencias_emitirCopia_btn.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 30, 0, 0);
        jPanel2.add(Licencias_emitirCopia_btn, gridBagConstraints);

        Licencias_emitir_btn.setBackground(new java.awt.Color(27, 140, 188));
        Licencias_emitir_btn.setForeground(new java.awt.Color(255, 255, 255));
        Licencias_emitir_btn.setText("Emitir");
        Licencias_emitir_btn.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 20, 42);
        jPanel2.add(Licencias_emitir_btn, gridBagConstraints);

        Licencias_renovar_btn.setBackground(new java.awt.Color(27, 140, 188));
        Licencias_renovar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Licencias_renovar_btn.setText("Renovar");
        Licencias_renovar_btn.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 10, 0, 42);
        jPanel2.add(Licencias_renovar_btn, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Seleccione una o más licencias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 0, 0);
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Emitir licencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 0);
        jPanel2.add(jLabel13, gridBagConstraints);

        jLabel14.setText("Observaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        jPanel2.add(jLabel14, gridBagConstraints);

        jLabel15.setText("Clase");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 0, 0);
        jPanel2.add(jLabel15, gridBagConstraints);

        Licencias_emitir_clase.setBackground(new java.awt.Color(252, 252, 252));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 30, 0, 42);
        jPanel2.add(Licencias_emitir_clase, gridBagConstraints);

        mod_titular_observaciones.setColumns(20);
        mod_titular_observaciones.setLineWrap(true);
        mod_titular_observaciones.setRows(5);
        jScrollPane2.setViewportView(mod_titular_observaciones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 394;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 40, 20, 0);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void mod_titular_esDonanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_titular_esDonanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mod_titular_esDonanteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Licencias_emitirCopia_btn;
    public javax.swing.JButton Licencias_emitir_btn;
    public javax.swing.JComboBox<Item> Licencias_emitir_clase;
    public javax.swing.JButton Licencias_renovar_btn;
    public javax.swing.JTable Licencias_tabla;
    public javax.swing.JButton Mod_titular_editar1;
    public com.toedter.calendar.JDateChooser Mod_titular_fechanac;
    public javax.swing.JComboBox<String> Mod_titular_gruposanguineo;
    public javax.swing.JComboBox<String> Mod_titular_tipodni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mod_titular_altura;
    private javax.swing.JTextField mod_titular_apellido;
    private javax.swing.JTextField mod_titular_calle;
    private javax.swing.JCheckBox mod_titular_esDonante;
    private javax.swing.JTextField mod_titular_nombre;
    private javax.swing.JTextField mod_titular_nroDNI;
    private javax.swing.JTextArea mod_titular_observaciones;
    public javax.swing.JButton mod_titular_volverBtn;
    // End of variables declaration//GEN-END:variables

    public void setTitular(TitularDTO titularDTO) {
        //este metodo recibe el DTO del titular y llena los campos
        mod_titular_nombre.setText(titularDTO.getNombre());
        mod_titular_apellido.setText(titularDTO.getApellido());
        mod_titular_nroDNI.setText(titularDTO.getNumDNI());
        Mod_titular_tipodni.setSelectedItem(TipoDocumento.valueOf(titularDTO.getTipoDoc()));
        mod_titular_altura.setText(titularDTO.getAltura());
        mod_titular_calle.setText(titularDTO.getCalle());
        mod_titular_esDonante.setSelected(titularDTO.isDonante());
        Mod_titular_fechanac.setDate(titularDTO.getFechaNacimiento());
    }
    
    public void setMain (TitularesMain main){
        this.main = main;
    }

    public TitularDTO getTitularDTO(){

            return new TitularDTO(
                this.mod_titular_nombre.getText().toString().trim(),
                this.mod_titular_apellido.getText().toString().trim(),
                this.Mod_titular_tipodni.getSelectedItem().toString(),
                this.mod_titular_nroDNI.getText().toString().trim(),
                this.Mod_titular_gruposanguineo.getSelectedItem().toString(),
                this.Mod_titular_fechanac.getDate(),
                this.mod_titular_esDonante.isSelected(),
                this.mod_titular_calle.getText().toString().trim(),
                this.mod_titular_altura.getText().toString().trim()
            ); 

    }

	public LicenciaDTO getLicenciaDTO() {
		return new LicenciaDTO(
            (Item) this.Licencias_emitir_clase.getSelectedItem(),
            this.mod_titular_observaciones.getText());
	}

    public void mostrarLicencia(LicenciaDTO licenciaDTO) {
        new LicenciaEmitidaFrame(licenciaDTO);
    }
    
}
