/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.metodos.licencias.view;

import com.metodos.licencias.DTO.LicenciaDTO;
import com.metodos.licencias.DTO.UsuarioDTO;
import com.metodos.licencias.controller.LicenciasController;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;

/**
 *
 * @author valec
 */
@Component
public class Licencias extends javax.swing.JPanel {

    int cornerRadius = 15;
    private Color grisOscuro = new Color(80,80,80);

    
    /**
     * Creates new form Licencias
     */
    public Licencias() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new RoundedPanel(30);
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLicencias = new javax.swing.JTable();
        nombre = new RoundedTextField(cornerRadius,grisOscuro);
        apellido = new RoundedTextField(cornerRadius,grisOscuro);
        vigente = new javax.swing.JCheckBox();
        grupoSanguineo = new RoundedComboBox(cornerRadius,grisOscuro);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buscarBtn = new RoundedButton(cornerRadius);
        imprimirBtn = new RoundedButton(cornerRadius);
        esDonante = new RoundedComboBox(cornerRadius,grisOscuro);
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(194, 194, 194));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        tablaLicencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Licencia", "Nombre", "Apellido", "Clase", "Inicio Vigencia", "Fin Vigencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaLicencias);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 30, 30);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 10);
        jPanel1.add(nombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanel1.add(apellido, gridBagConstraints);

        vigente.setBackground(new java.awt.Color(252, 252, 252));
        vigente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        vigente.setText("Vigente");
        vigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(vigente, gridBagConstraints);

        grupoSanguineo.setBackground(new java.awt.Color(252, 252, 252));
        grupoSanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanel1.add(grupoSanguineo, gridBagConstraints);

        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel5.setText("Grupo sanguíneo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        buscarBtn.setBackground(new java.awt.Color(27, 140, 188));
        buscarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupita_chica.png"))); // NOI18N
        buscarBtn.setBorder(null);
        buscarBtn.setBorderPainted(false);
        buscarBtn.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 30);
        jPanel1.add(buscarBtn, gridBagConstraints);

        imprimirBtn.setBackground(new java.awt.Color(27, 140, 188));
        imprimirBtn.setForeground(new java.awt.Color(255, 255, 255));
        imprimirBtn.setText("Imprimir");
        imprimirBtn.setEnabled(false);
        imprimirBtn.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 30);
        jPanel1.add(imprimirBtn, gridBagConstraints);

        esDonante.setBackground(new java.awt.Color(252, 252, 252));
        esDonante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Es donante", "No es donante" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanel1.add(esDonante, gridBagConstraints);

        jLabel4.setText("Condicion donador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Listado de licencias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jLabel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 650;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void vigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigenteActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    public javax.swing.JButton buscarBtn;
    private javax.swing.JComboBox<String> esDonante;
    public javax.swing.JComboBox<String> grupoSanguineo;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    public javax.swing.JTable tablaLicencias;
    private javax.swing.JCheckBox vigente;
    // End of variables declaration//GEN-END:variables

public void clearTable(){
        DefaultTableModel tableModel = (DefaultTableModel) tablaLicencias.getModel();
        tableModel.setRowCount(0);
    }

public void cargarTabla(LicenciaDTO licencia){
        DefaultTableModel tableModel = (DefaultTableModel) tablaLicencias.getModel();
        Object[] dataRow = {licencia.getNumeroLicencia(),licencia.getNombreTitular(),licencia.getApellidoTitular(),licencia.getTipoLicencia().getAtributo1(),licencia.getInicioVigencia(),licencia.getFinVigencia()};
        tableModel.addRow(dataRow);
    }

public String getNombre(){
    return nombre.getText();
}

public String getApellido(){
    return apellido.getText();
}

public String getGrupoSanguineo(){
    return grupoSanguineo.getSelectedItem().toString();
}

public String getCondicionDonante(){
    return esDonante.getSelectedItem().toString();
}

public boolean getVigencia(){
    return vigente.isSelected();
}

    public void addSearchButtonListener(LicenciasController.SearchButtonListener searchButtonListener) {
        buscarBtn.addActionListener(searchButtonListener);
    }

}
