/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.metodos.licencias.view;

import com.metodos.licencias.DTO.LicenciaDTO;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author valec
 */
public class LicenciaEmitidaMain extends javax.swing.JPanel {

    /**
     * Creates new form LicenciaEmitidaMain
     */
    
    CardLayout cl;
    int cornerRadius = 15;
    Color grisOscuro = new Color(80,80,80);
    
    public LicenciaEmitidaMain(LicenciaDTO licencia) {
        initComponents();
        armarCardLayout(licencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardPanel = new RoundedPanel(15);
        licenciaPanel = new RoundedPanel(15);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tipoLicencia = new RoundedLabel(cornerRadius,grisOscuro);
        nroLicencia = new RoundedLabel(cornerRadius,grisOscuro);
        inicioLicencia = new RoundedLabel(cornerRadius,grisOscuro);
        finLicencia = new RoundedLabel(cornerRadius,grisOscuro);
        observaciones = new RoundedLabel(cornerRadius,grisOscuro);
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new RoundedButton(15);
        jButton2 = new RoundedButton(15);
        pdfPanel = new RoundedPanel(15);
        volverBtn = new RoundedButton(15);
        PDFPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new RoundedButton(15);

        setBackground(new java.awt.Color(194, 194, 194));
        setLayout(new java.awt.GridBagLayout());

        cardPanel.setBackground(new java.awt.Color(252, 252, 252));
        cardPanel.setLayout(new java.awt.CardLayout());

        licenciaPanel.setBackground(new java.awt.Color(252, 252, 252));
        licenciaPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Licencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        licenciaPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("nroLicencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 30);
        licenciaPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        licenciaPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("fin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 30);
        licenciaPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        licenciaPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Observaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        licenciaPanel.add(jLabel6, gridBagConstraints);

        tipoLicencia.setBackground(new java.awt.Color(252, 252, 252));
        tipoLicencia.setForeground(new java.awt.Color(80, 80, 80));
        tipoLicencia.setText("jLabel7");
        tipoLicencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 10);
        licenciaPanel.add(tipoLicencia, gridBagConstraints);

        nroLicencia.setBackground(new java.awt.Color(252, 252, 252));
        nroLicencia.setForeground(new java.awt.Color(80, 80, 80));
        nroLicencia.setText("jLabel8");
        nroLicencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 30);
        licenciaPanel.add(nroLicencia, gridBagConstraints);

        inicioLicencia.setBackground(new java.awt.Color(252, 252, 252));
        inicioLicencia.setForeground(new java.awt.Color(80, 80, 80));
        inicioLicencia.setText("jLabel9");
        inicioLicencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 10);
        licenciaPanel.add(inicioLicencia, gridBagConstraints);

        finLicencia.setBackground(new java.awt.Color(252, 252, 252));
        finLicencia.setForeground(new java.awt.Color(80, 80, 80));
        finLicencia.setText("jLabel10");
        finLicencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 30);
        licenciaPanel.add(finLicencia, gridBagConstraints);

        observaciones.setBackground(new java.awt.Color(252, 252, 252));
        observaciones.setForeground(new java.awt.Color(80, 80, 80));
        observaciones.setText("jLabel11");
        observaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 10, 30);
        licenciaPanel.add(observaciones, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 30);
        licenciaPanel.add(jPanel2, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(27, 140, 188));
        jButton1.setForeground(new java.awt.Color(252, 252, 252));
        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1JButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 10);
        licenciaPanel.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(27, 140, 188));
        jButton2.setForeground(new java.awt.Color(252, 252, 252));
        jButton2.setText("to pdf land");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2JButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 30);
        licenciaPanel.add(jButton2, gridBagConstraints);

        cardPanel.add(licenciaPanel, "Panel");

        pdfPanel.setBackground(new java.awt.Color(252, 252, 252));
        pdfPanel.setLayout(new java.awt.GridBagLayout());

        volverBtn.setBackground(new java.awt.Color(27, 140, 188));
        volverBtn.setForeground(new java.awt.Color(252, 252, 252));
        volverBtn.setText("go back pls");
        volverBtn.setFocusable(false);
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pdfPanel.add(volverBtn, gridBagConstraints);

        PDFPanel.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("pdf a imprimir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PDFPanel.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 30);
        pdfPanel.add(PDFPanel, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(27, 140, 188));
        jButton3.setForeground(new java.awt.Color(252, 252, 252));
        jButton3.setText("print (kills a tree)");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pdfPanel.add(jButton3, gridBagConstraints);

        cardPanel.add(pdfPanel, "PDF");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cardPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1JButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1JButton1ActionPerformed

    private void jButton2JButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2JButton2ActionPerformed
        switchScreen("PDF");
    }//GEN-LAST:event_jButton2JButton2ActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        switchScreen("Panel");
    }//GEN-LAST:event_volverBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PDFPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel finLicencia;
    private javax.swing.JLabel inicioLicencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel licenciaPanel;
    private javax.swing.JLabel nroLicencia;
    private javax.swing.JLabel observaciones;
    private javax.swing.JPanel pdfPanel;
    private javax.swing.JLabel tipoLicencia;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void armarCardLayout(LicenciaDTO licencia){

        cl = (CardLayout) (cardPanel.getLayout());
        
        tipoLicencia.setText(" " + licencia.getTipoLicencia().getAtributo1());
        //nroLicencia.setText(licencia.getNumeroLicencia().toString());
        //inicioLicencia.setText(licencia.getInicioVigencia().toString());
        //finLicencia.setText(licencia.getFinVigencia().toString());
        observaciones.setText(" " + licencia.getObservaciones());
        
    }
    
    public void switchScreen (String pantalla) {    
      cl.show(cardPanel, pantalla);
      revalidate();
    } 

}
